### ISSUE TITLE
Multiple recordings? 

### ISSUE THREAD

**Issue by spenceropope** [jsierles/react-native-audio#10]
How would I record and playback multiple files (either at the same time or only one at a time)?

**Comment by jsierles** [comment]
This isn't possible right now, since native modules are singletons. This will work once this component is modified to be a full React Native component, renderable with child views (such as controls). I have this on the list but not sure when I'll get to it. PRs welcome :)

**Comment by jsierles** [comment]
One more option today is to use this component just to record, and use react-native-video to do playback. Then you can setup multiple players without a problem.

**Comment by spenceropope** [comment]
alright, thank you
