### ISSUE TITLE
AMR on iOS

### ISSUE THREAD

**Issue by marko89kv** [jsierles/react-native-audio#100]
Is there a way to support AMR format on iOS?

**Comment by jsierles** [comment]
Yes, would you be up for submitting a PR to add the new codecs listed here that aren't already supported?

https://developer.apple.com/reference/coreaudio/1572096-audio_data_format_identifiers

**Comment by marko89kv** [comment]
To be honest, I haven't touched Objective-C in a while, but I will have to :))
I'll fork and try to make something of it, and report back. Since my app deadline is in about a month from now, and I still have to finish the android version, I can start working on it in 10 days or so.

**Comment by jsierles** [comment]
Ok, I'll probably do another small release sooner and can add it for you.

**Comment by marko89kv** [comment]
I just saw the notification... You sir are a hero we need, not a one we deserve ;)
