### ISSUE TITLE
Does this audio file have saved into the phone?

### ISSUE THREAD

**Issue by slipy-spy** [jsierles/react-native-audio#104]
I try to send a audio file to the others, then click it to play,but I can't  found the audio I send.

**Comment by zhiquan-yu** [comment]
@slipy-spy The `audioPath` is what you need.
```JavaScript
let audioPath = AudioUtils.DocumentDirectoryPath + '/test.aac';
AudioRecorder.prepareRecordingAtPath(audioPath, options)
```

**Comment by zhiquan-yu** [comment]
@slipy-spy `AudioUtils.DocumentDirectoryPath + 'test.aac'` is what you need.
