### ISSUE TITLE
vorbis encoding in android doesn't work

### ISSUE THREAD

**Issue by arisAlexis** [jsierles/react-native-audio#105]
working with aac but when you specify vorbis encoding crash happens with just "start failed". 
android version 5.1.1, oxygen os 2.1.2

**Comment by RakanNimer** [comment]
Hey, thanks for reporting this.
I might have an idea why it's happening. I'll look into it soon and get back to you.

**Comment by jsierles** [comment]
Any resolution here?

**Comment by jsierles** [comment]
Closing this out for now. Feel free to reopen if the issue persists!
