### ISSUE TITLE
Can I upload the audio file to server with a presigned URL?

### ISSUE THREAD

**Issue by zhiquan-yu** [jsierles/react-native-audio#107]
2016-11-02 21:29 I have the answer: Yes, I can.

What is presigned URL?: [React Native: Upload (any) file to S3 with a presigned URL](http://blog.rudikovac.com/react-native-upload-any-file-to-s3-with-a-presigned-url/)

I used this way upload image success, but upload audio fail, the server has received the audio file, but size is 0, I have no idea, please help!

> I used [react-native-fileupload](https://github.com/PhilippKrone/react-native-fileupload) upload audio file success, but react-native-fileupload can not run on Android, and it seems that no one to maintain.

> I noticed this: https://github.com/jsierles/react-native-audio/issues/97
@RakanNimer said: If you want to upload and download voice files then using react-native-fs would be a great idea.

```JavaScript
  uploadAudio = async () => {
    const path = `${AudioUtils.DocumentDirectoryPath}/test.aac`
    const formData = new FormData()
    formData.append('file', {
      uri: path,
      name: 'test.aac',
      type: 'audio/aac',
    })
    try {
      const res = await fetch(API_UPLOAD_MSG_FILE, {
        method: 'POST',
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        body: formData,
      })
      const json = await res.json()
    } catch (err) {
      alert(err)
    }
  }
```

**Comment by Sumrocks** [comment]
Hi，man
do you fix it？

**Comment by zhiquan-yu** [comment]
@Sumrocks Yes, use `const path = 'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac'`. On Android, you must add `file://`.

**Comment by Sumrocks** [comment]
TKS soooooo much !!! it work

**Comment by Noitidart** [comment]
Hi there, thanks for this question.

And @zhiquan-yu thanks for your answer. However it is required by the endpoint I am hitting, for me to set `'Content-Type': 'audio/acc'`. If I do this, react-native gives me this error:



I tried with `'Content-Type':'multipart/form-data'` however my end point returns errors.

This is my code:

```
    const data = new FormData();
    const ext = 'acc';
    data.append('file', {
        uri:`file://${file_path}`,
        name:`recording.${ext}`,
        type:`audio/${ext}`
    }, `recording.${ext}`);

    const response = await fetch('https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true', {
        method: 'POST',
        headers: {
            // 'Content-Type': `audio/${ext}`,
            'Content-Type': 'multipart/form-data',
            'X-Watson-Authorization-Token': token
        },
        body: data
    });

    console.log('watson-stt::getResults - response:', response);

    if (response.status !== 200) {
        const error = await response.text();
        throw new Error(`Got bad response "status" (${response.status}) from Watson Speach to Text server, error: "${error}"`);
    }
    
```

**Comment by daxaxelrod** [comment]
+1

**Comment by gregbenner** [comment]
You want `'Content-Type': 'multipart/form-data'` for sure,
Your filetype or meta type is extracted from `type:audio/${ext}`
I would ensure you are in production mode, to avoid the chrome debugger being open (which kills the request) Also console.log your ${file_path} to ensure you aren't doubling file:///

**Comment by Noitidart** [comment]
@gregbenner thanks for that comment, can you please show example. I'm not sure where to put `type:audio/${ext}`.

**Comment by gregbenner** [comment]
This is what I used https://github.com/expo/expo/issues/214#issuecomment-316950941
The server if Node needs to use `multer`

**Comment by gregbenner** [comment]
Did that help @Noitidart  ?

**Comment by Biplovkumar** [comment]
_upload = async () => {

let apiUrl = 'http://103.234.184.240/api_for_solutions/upload_recording';

           const path = 'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac';

            const formData = new FormData();
            formData.append('file', {
                uri: path,
                name: 'test.aac',
                type: 'audio/aac',
            })
            fetch(apiUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'multipart/form-data',
      
                },
                body: formData
            }).then(response => {
                console.error(response)
            }).catch(err => {
                console.error(err)
            })

}


#######################

output:-network request failed

plzz solve my error,i am new in react.
thanks in advance

**Comment by gregbenner** [comment]
@Biplovkumar copy paste this https://github.com/expo/expo/issues/214#issuecomment-316950941

**Comment by ShooterArk** [comment]
@gregbenner I have copied you code as well, still I am getting the same network request error.. Is it related to fetch? I mean should I use third party plugin like axios or fetch-blob ?

**Comment by saad65** [comment]
hey @ShooterArk @Biplovkumar did you find a solution to this?

**Comment by muhammadashfaq** [comment]
> @SumRocks Yes, use `const path = 'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac'`. On Android, you must add `file://`.

not working
any help please
