### ISSUE TITLE
Playback of bundled files doesn't work on iOS simulator

### ISSUE THREAD

**Issue by tomprogers** [jsierles/react-native-audio#110]
I used this module to record an audio file (lpcm format). Then I extracted that file, bundled it into the app, and added a button that plays the file from the bundle directory.

In the iOS simulator, playback does not occur, but no errors or warnings are thrown. When running on a real hardware device, playback works great.

I don't know if this is a limitation of the simulators or an issue with this module. In either case, it's probably worth documenting in the README.

**Comment by jsierles** [comment]
This is interesting - would you be up for adding a PR for this?

**Comment by tomprogers** [comment]
Sorry -- I'm neither an Obj-C nor Swift dev, and I really don't understand Apple's technology or ecosystem. The problem does not appear to be within the javascript, which is where my expertise ends.
