### ISSUE TITLE
Audio is playing in receiver instead of device speaker (iOS)

### ISSUE THREAD

**Issue by pottercomuneo** [jsierles/react-native-audio#114]
This is what is happening to me, I'm using the example scene. I would like to play the sound on the speakers, how can I set this?

**Comment by tomprogers** [comment]
This is a good question.

**Comment by GingerBear** [comment]
I found it's playing on speaker if I add `sound.setCategory("Playback");` before `sound.play(...)`

**Comment by RakanNimer** [comment]
Feels more like an issue for react-native-sound. Safe to close ?
