### ISSUE TITLE
android 6.0, ERROR :stop failed  and start failed 

### ISSUE THREAD

**Issue by Sumrocks** [jsierles/react-native-audio#120]
due to Authorization ???
if so ,
How to use    "AudioRecorder.requestAuthorization","AudioRecorder.checkAuthorizationStatus"?

**Comment by Sumrocks** [comment]
start failed due to Authorization!  but how to use  checkAuthorizationStatus???
stop failed is bugs in android  ,resolved  ==>pull request #108

**Comment by jsierles** [comment]
You may need to add this to your AndroidManifest.xml: `<uses-permission android:name="android.permission.RECORD_AUDIO" />`

Feel free to reopen again if you still have problems!

**Comment by Sumrocks** [comment]
stop failed is bugs in android  ！
try{
     recorder.stop();
}catch(final Exception e){

}

```

@ReactMethod
  public void stopRecording(Promise promise){
    if (!isRecording){
      Log.e("INVALID_STATE", "Please call startRecording before stopping recording");
      promise.reject("INVALID_STATE", "Please call startRecording before stopping recording");
      return;
    }
    recorder.stop();
    isRecording = false;
    recorder.release();
    promise.resolve(currentOutputFile);
    sendEvent("recordingFinished", null);
  }

```

**Comment by jsierles** [comment]
I don't understand this bug report. Can you clarify? If you have a solution, also, please submit as a PR. Thanks!

**Comment by morneluckybeard** [comment]
I'm experiencing the same issue here. If you call the stopRecording method when the startRecording promise resolves it throws the "Please call startRecording before stopping recording". 

I think the state needs to change before you resolve the promise. You should have to be able to cancel the recording in the promise resolution e.g. 

`audioRecorder.startRecording().then(res => {audioRecorder.stopRecording()})`

The above line throws throws the "Please call startRecording before stopping recording" error at the moment.

@jsierles is this something you can look into?
