### ISSUE TITLE
Android: Could not retrieve file for uri /data/user/0/com.babyshow/files/gougou.aac

### ISSUE THREAD

**Issue by hyq2015** [jsierles/react-native-audio#125]
after I recorded the audio,audio can play by the method AudioRecorder.playRecording(),
but when I try to upload the audio to server,there is an error:Could not retrieve file for uri /data/user/0/com.babyshow/files/gougou.aac

this is weird, I have set the correct audio path by : let audioPath = AudioUtils.DocumentDirectoryPath +'/gougou.aac'; seems like the audio file dose not save in the audioPath.
waitting for your kindly answer,tks!

**Comment by Sumrocks** [comment]
Ah, i have the same problem

**Comment by Sumrocks** [comment]
#107 issue  fix it！
when you upload, path should be  => 'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac'. On Android, you must add file://.

**Comment by hyq2015** [comment]
cheers! it works! thank you~

**Comment by anikasetia** [comment]
Hi, I am facing the same issue, I used the solution proposed. On prepending 'file://' to the path I am facing this error "Value for uri cannot be cast from ReadableNativeMap to String". Can anyone help me out with this?

**Comment by fahadjabbar8** [comment]
If you are hard coding a uri it will give the same error even though the path is valid. it should be a variable!

**Comment by tlweiii6465** [comment]
hi after i added  'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac' for post .acc file to my server it was success upload but the .acc inside my server was crash is that any solution? this issue is only occur in android

**Comment by Rishabh-Rathod** [comment]
> hi after i added 'file://' + AudioUtils.DocumentDirectoryPath + 'test.aac' for post .acc file to my server it was success upload but the .acc inside my server was crash is that any solution? this issue is only occur in android

".acc" ? make sure it is ".aac" while sending it.
