### ISSUE TITLE
recordingFinished is never received

### ISSUE THREAD

**Issue by skv-headless** [jsierles/react-native-audio#13]
basically I tried implement #1. 
https://github.com/jsierles/react-native-audio/blob/master/AudioExample/index.ios.js#L36
This code is never executed. If you have another behaviour please let me know.

**Comment by jsierles** [comment]
I'll take a look at this - haven't checked this component in a while as I'm not actively using it.

**Comment by jsierles** [comment]
This should now be fixed on master. Would love to see a PR for audio settings!
