### ISSUE TITLE
Android support for lpcm recording.

### ISSUE THREAD

**Issue by ohtangza** [jsierles/react-native-audio#131]
PCM is the most basic format. Is there any plan to support to record lpcm format in Android?

**Comment by jsierles** [comment]
I don't think this can be done using `MediaRecorder'. We're only supporting formats listed here: https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat.html

I'm not too familiar with Android - so going to close this in favor of a PR if someone knows how to do it.
