### ISSUE TITLE
getDuration return 0 first time

### ISSUE THREAD

**Issue by MirGhojam** [jsierles/react-native-audio#132]

**Comment by jsierles** [comment]
Can you specify which platform and environment? Device or simulator?

**Comment by jsierles** [comment]
Closing this out. Feel free to reopen if the issue persists!

**Comment by NoelBroda** [comment]
Obviously, this issue is 100% related to this one: https://github.com/jsierles/react-native-audio/issues/115

You are trying to get the file duration, when actually the file was not totally created yet.
We need promises. Always we are dealing with files, we need promises.

**Comment by jsierles** [comment]
Unfortunately we have no way to know when the file is finished writing. Check #115 for more discussion on solutions for this.
