### ISSUE TITLE
playWithUrl not working anymore.

### ISSUE THREAD

**Issue by laclance** [jsierles/react-native-audio#133]
I am trying to play back text with playWithUrl, it used to work but it is not working anymore. If I copy the url to the browser it plays fine.

react-native: v0.39.2
react-native-audio: v2.2.0
iOs: 10
osx: 10.11.6

**Comment by jsierles** [comment]
Are you still having this issue? In the next version, we're going to deprecate playback soon in favor of https://github.com/zmxv/react-native-sound, since we plan to integrate with this library. So closing this out for now. Thanks!

**Comment by laclance** [comment]
Yes i am. So will there be a text to speech function?
