### ISSUE TITLE
ios amr cannot record and play? I read your readme, it said support amr. 

### ISSUE THREAD

**Issue by MingYe-dz** [jsierles/react-native-audio#135]

**Comment by jsierles** [comment]
Thanks! Should be fixed in 30d075c9ce7942be65bcd02cd8e6bbda23a6f26b, and release 2.4.0.

**Comment by mikedream89** [comment]
@jsierles the problem was fixed? but i can not record on ios

**Comment by marlti7** [comment]
alaways problem
