### ISSUE TITLE
[iOS] How can I support "amr"

### ISSUE THREAD

**Issue by literature** [jsierles/react-native-audio#137]
state = {
      currentTime: 0.0,
      recording: false,
      stoppedRecording: false,
      finished: false,
      audioPath: AudioUtils.DocumentDirectoryPath + '/wxx.amr'
    };

    prepareRecordingPath(audioPath){
      AudioRecorder.prepareRecordingAtPath(audioPath, {
        SampleRate: 22050,
        Channels: 1,
        AudioQuality: "Low",
        AudioEncoding: "amr",
        AudioEncodingBitRate: 32000
      });
    }

but Xcode run  have an error 
`2016-12-28 15:33:17.749 [info][tid:com.facebook.react.JavaScript] Running application "AudioExample" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2016-12-28 15:33:24.250 AudioExample[4519:1323883] error: The operation couldn’t be completed. (OSStatus error 1718449215.)`

**Comment by ma762614600** [comment]
I have the same error: " Error Domain=NSOSStatusErrorDomain Code=1718449215 "(null)" "
`_prepareRecord(){
        let path = documentDirectoryPath() + '/' + 'Video/1.amr';
    }`

**Comment by jsierles** [comment]
Try using the `AudioEncoding` option. Either `amr` on iOS or `amr_wb` on Android.

**Comment by saman-may** [comment]
> Try using the `AudioEncoding` option. Either `amr` on iOS or `amr_wb` on Android.

It's not working. Noting happens when press record.
It just records when encoding is 'aac'

**Comment by meiqi1992** [comment]
@saman-may same issue～  you had resolved?

**Comment by marlti7** [comment]
same problem . why close
