### ISSUE TITLE
Unused Entity Issue - Xcode Warning for variable time

### ISSUE THREAD

**Issue by rhaker** [jsierles/react-native-audio#15]
Hi Joshua, Thanks for putting together this package. Really appreciate it. Xcode 6.4 is giving me an "Unused Entity Issue" warning for variable "time" in both AudioRecorderManager.m and AudioPlayerManager.m. I don't see this variable being used in the code. Perhaps I'm missing something here? Thanks.

**Comment by jsierles** [comment]
Thanks for the heads up -this is fixed in v 0.2.1
