### ISSUE TITLE
Help with audio encoding and other options

### ISSUE THREAD

**Issue by dccarmo** [jsierles/react-native-audio#152]
I'm using react-native-audio to get voice data and then send that to Nuance so they can do the speech to text conversion. I'm not super smart with audio properties, so I'm not sure what am I doing wrong.

The Nuance docs says that they support these input formats:

![screen shot 2017-01-26 at 19 01 36](https://cloud.githubusercontent.com/assets/638474/22350170/e3043d42-e3f9-11e6-919b-6a57dff9152f.png)

Taken from here: https://developer.nuance.com/downloads/guidelines/Nuance%20Audio%20Input%20Specification_v11_ND.pdf

Now given the specification, I assume the only option I have is to send an audio with the `PCM	16k-16b—256kbps` format. 

Here's what I thought the parameters for `AudioRecorder` should be:

```
AudioRecorder.prepareRecordingAtPath(audioPath, {
  SampleRate: 16000,
  Channels: 1,
  AudioQuality: 'Low',
  AudioEncoding: 'lpcm'
});
```

When I send the recorded audio with these options, Nuance returns me with an error saying wrong format. Is there something I'm missing?

Also, the `lpcm` format is only available for iOS. From the table, there's not a format that would cover both platforms given react-native-audio supported formats, right?

**Comment by jsierles** [comment]
I'm not sure why Nuance would report that error. Maybe best to contact support there with the file?

For Android we're using this: https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html

I think it's possible to record other formats on Android, but I don't know the platform too well. MediaRecorder seems to only support the formats listed above. Sorry I couldn't help more here!

**Comment by dccarmo** [comment]
@jsierles I added more options to `AVAudioRecorder` and managed to get a successful response from them, but still, not what I expected. I suspect their HTTP platform is not being maintained anymore. Either way, I'll close this. Thanks for the help!
