### ISSUE TITLE
unable to play when testing on ios - AudioExample

### ISSUE THREAD

**Issue by dturton** [jsierles/react-native-audio#153]
The operation couldn’t be completed. (OSStatus error 2003334207. Do I need to change the "audioPath" to make it work?

**Comment by dannyyaou** [comment]
Me, too
Please

**Comment by cooperka** [comment]
The example app works for me on latest master, tested on iPhone 6s simulator with iOS 10.2. Can you both provide more details about your setup please?

**Comment by dturton** [comment]
Yes on the simulator it works just fine. Its when you test it on a physical iPhone. I tested on a iPhone 7 Plus ios 10.2.1 and it doesn't work.

**Comment by cooperka** [comment]
Ah, I get the same error if I try playing directly before stopping. Make sure you click "STOP" first, then you can play. Here's my error if I try to play before stopping:

```js
failed to load the sound:
{
  code: "ENSOSSTATUSERRORDOMAIN2003334207",
  domain: "NSOSStatusErrorDomain",
  message: "The operation couldn’t be completed. (OSStatus error 2003334207.)"
}
```

**Comment by cooperka** [comment]
Seems related to https://github.com/zmxv/react-native-sound/issues/89
