### ISSUE TITLE
Questions about getting started

### ISSUE THREAD

**Issue by tgoldenberg** [jsierles/react-native-audio#16]
So I tried to use the project in 2 ways. When I tried to clone the project, `npm install`, and run, I got several errors. Xcode tells me: `<Error>: CGContextTranslateCTM: invalid context 0x0.`. I post some screenshots below to debug better. 

Second, when I follow the installation instructions, on simply adding the 4 AudioPlayer/AudioRecorderManager files in my project, I find that they aren't loading as `NativeModules`. I tested this by console.logging the `NativeModules`, and the AudioPlayerManager and AudioRecorderManager were not included. 

Any suggestions? Thank you! Below are screenshots to help see the problems more clearly. 
<img width="293" alt="screen shot 2015-10-17 at 2 48 50 pm" src="https://cloud.githubusercontent.com/assets/10930134/10560632/bef9420c-74de-11e5-8ba3-df4b664ac8ec.png">
<img width="298" alt="screen shot 2015-10-17 at 2 48 37 pm" src="https://cloud.githubusercontent.com/assets/10930134/10560634/c442be32-74de-11e5-9207-641029429f3f.png">
<img width="525" alt="screen shot 2015-10-17 at 2 48 32 pm" src="https://cloud.githubusercontent.com/assets/10930134/10560637/c8e9091e-74de-11e5-8060-70694e67e3b6.png">

**Comment by tgoldenberg** [comment]
So I am able to access the AudioPlayerManager now through NativeModules. But when I try to play a file with a relative path, I don't get any audio. `AudioPlayerManager.play('../audio/english.mp3');`. Any suggestions? Sorry to be a nuisance, but I am really excited to get this working :)

**Comment by tgoldenberg** [comment]
Got sound finally. It is a little confusing, because I had do a lot of `cd`... in the terminal to find the right extension, and it was a little bit strange, but oh well. As I continue to use this, maybe I can help contribute to the documentation. I tried a few other RN audio libraries, and all of them are not exactly easy to start using :)

**Comment by jsierles** [comment]
Thanks for the offer - the docs could use some help! Soon I'll be adding some more features to this, along with documentation. As you discovered, mp3 is not the target format. The best way to learn how to use it is looking at the example project. Here's the relevant line with the file extension: https://github.com/jsierles/react-native-audio/blob/master/AudioExample/index.ios.js#L31

FYI, the errors you saw earlier are related to a harmless bug in React Native, and an issue on iOS 9 which requires a special value in your Info.plist file. These have nothing to do with this component.

Thanks for your interest, and please do send a PR! :)

**Comment by tgoldenberg** [comment]
@jsierles Thank you, this is a very cool project. I look forward to using it more and will try to make any contribution I can think of!
