### ISSUE TITLE
Record your speech and convert it to text.

### ISSUE THREAD

**Issue by e-rasvet** [jsierles/react-native-audio#163]
Hello!

I found this line in project description: "This sample uses the microphone to record your speech and convert it to text."

Could you show example of code for speech to text? (iOS)

**Comment by RakanNimer** [comment]
The string is an example description of a feature one could build with this library. 
It's used to explain to the user why you need the microphone. 

This module doesn't support speech to text, for this kind of features I recommend checking out [the watson api](https://developer.ibm.com/watson/)
