### ISSUE TITLE
Crashed by "AudioRecorderManager.checkAuthorizationStatus"

### ISSUE THREAD

**Issue by Samoy** [jsierles/react-native-audio#164]
Like this picture:
![image](https://cloud.githubusercontent.com/assets/16362570/23950202/1ef39fc8-09c5-11e7-8700-9d8aa39d4e6e.png)

**Comment by chmac** [comment]
Did you add the message to your `Info.plist` file that tells the user why you need the microphone permission?

I saw this error, then I added the message, then I restarted it all, and now it's running on both the simulator and a physical device.

**Comment by WajeehZantout** [comment]
Hello, am facing the same above error.
RN: "0.42.0", Android OS v 7.0

**Comment by WajeehZantout** [comment]
I fixed that issue! I linked the library manually in Android

**Comment by WajeehZantout** [comment]
@RakanNimer Please add the manual linking of the library in Android in case react-native link react-native-audio failed

**Comment by brainbrain34** [comment]
In my case i solved to work on iOS and Android, the problems was the react-native link don't work correctly for android i had to link manually on **MainApplication.java**:
`
**import com.rnim.rn.audio.ReactNativeAudioPackage;**
...
 protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
           **new ReactNativeAudioPackage()**
  );
  }
`
check as well **build.gradle**:
`
dependencies {
    **compile project(':react-native-audio')**
}
`
and finally on **settings.gradle:**
`
**include ':react-native-audio'
project(':react-native-audio').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-audio/android')**
`
That works for me ;)

**Comment by kagmanoj25** [comment]
I'm getting same issue in iOS.
