### ISSUE TITLE
Update record session category to AVAudioSessionCategoryMultiRoute in NPM

### ISSUE THREAD

**Issue by gerrod** [jsierles/react-native-audio#165]
Hi! I notice that you've updated the audio session category for iOS, as of this commit:

https://github.com/jsierles/react-native-audio/commit/ce8b62c5896b01365d76f849945abfb5c7123438

Would you be able to update the package in NPM to get this change too, please?

Also - as an aside - the version in NPM is 3.2.1, where-as the version here on GitHub is 3.1.0 -- however, even though the NPM version seems to be tracking ahead of the GitHub version, this change is missing... ??

**Comment by jsierles** [comment]
This change should be available in 3.2.1 - but in case it's not, I have published 3.2.2.

**Comment by gerrod** [comment]
Thanks so much! Yes, the `3.2.2` package has definitely fixed it. Cheers!
