### ISSUE TITLE
Call for a new maintainer

### ISSUE THREAD

**Issue by jsierles** [jsierles/react-native-audio#166]
Hey all - I'm not using this, or even working on React Native apps now. So I'd prefer someone who uses this library become the primary maintaner. @cooperka would you be interested/able? @RakanNimer?

Thanks!

**Comment by cooperka** [comment]
@jsierles I'm interested but not sure if I'd be able. I'm using this in a production app, but it's only a small part. What exactly would you expect of the primary maintainer?

**Comment by jsierles** [comment]
There isn't much to do - just answering issues, checking pull requests, publishing to npm. I'd say I only do an hour or two a month. But I figured someone who actually uses it would be better qualified to test changes :)

**Comment by RakanNimer** [comment]
Hey @jsierles, 
I haven't been very responsive in issue sorting as much as I would have liked.
Real life gets in the way :) 

We're using it in prod too, so would be happy to invest a couple of hours more a month to help maintain. 

Will start by going through the issues I can help with this weekend :) 

Cheers !

**Comment by NoelBroda** [comment]
👏 
Thank you for this @jsierles.

**Comment by jsierles** [comment]
Cool - yeah just a bit of help with issues and PRs would be good. Thanks everyone! I'll ensure all of you are contributors, so you are free to merge and tag versions as needed. I can then just publish when they're ready.

**Comment by jsierles** [comment]
Closing this issue, thanks for the responses.
