### ISSUE TITLE
Android can not find the file after the recording is complete and can not upload the file to the server

### ISSUE THREAD

**Issue by x4922** [jsierles/react-native-audio#169]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  3.2.2
react-native :0.41.2
react :  15.4.2
using react-native-sound ? Yes

### Expected behaviour :

What were you trying to do and what did you expect to happen ?

### Actual behaviour

What happened when your issue occurred ? The more details you provide here the better the odds are that someone will help you revolve your issue

### Steps to reproduce

Please provide us with some code that we can run to reproduce your error. 

### Link to a git repo that reproduces bug 

If you put a github repo that reproduces your issue than you significantly increase your chances of getting help !

**Comment by Sumrocks** [comment]
```
  if(Platform.OS ==='android'){
                    fileUrl = 'file://' + yourUrl;
                }else {
                    fileUrl = yourUrl;
                }
```

**Comment by x4922** [comment]
@Sumrocks  fileUrl = 'file://' + yourUrl; The resulting path is ‘file:///data/data/com.iflytimeapp/files/1491373278000.aac’
Upload file appears Network request failed.
But I will be a file into a picture('file:///storage/emulated/0/DCIM/IMG_20170405_142555.jpg') when the request can be successful

**Comment by x4922** [comment]
@Sumrocks And in the file directory I can not find this .acc file

**Comment by x4922** [comment]
@Sumrocks  upload code:
let audioData = new FormData();
          let path = this.props.path;
          if(Platform.OS ==='android'){
              path = 'file://' + path;
          }
          let name = path.split('/');
          name = name[name.length-1];
          audioData.append('file',{uri: path, type: 'application/octet-stream', name: name})
          audioData.append('timeline_id',msgId)
          audioData.append('sound_time',this.props.time)
          console.log(audioData);
          fetch(url,{
              method:'POST',
              headers:{  
                'Content-Type':'multipart/form-data',  
              }, 
              body:audioData
            }).then(res =>console.log(res))
        }

**Comment by Sumrocks** [comment]
Android  does not support .acc on some models.
 let audioType = Platform.OS ==='ios'?'.aac':'.amr';

**Comment by x4922** [comment]
@Sumrocks  Try to find other files or find the file but the use of sound This plugin is able to play the recording file

**Comment by Sumrocks** [comment]
```
 let fileUrl = '';
 let audioType = Platform.OS ==='ios'?'.aac':'.amr';
 if(Platform.OS ==='android'){
       fileUrl = 'file://' + myUrl;
  }else {
       fileUrl = myUrl;
 }
  let file = {uri:fileUrl, type:'multipart/form-data',name:'test'+audioType};
  let formData = new FormData();
  formData.append('file',file);

```
It works,I don't know if it helps.:)
