### ISSUE TITLE
When does Android&iOS support the network?

### ISSUE THREAD

**Issue by pheromone** [jsierles/react-native-audio#170]
When does Android&iOS support the network?

**Comment by cooperka** [comment]
@pheromone Do you mean playing audio from a web URL?

**Comment by pheromone** [comment]
yes. support?

**Comment by cooperka** [comment]
I don't think we do yet, but you could try https://github.com/tlenclos/react-native-audio-streaming. You could also download the file to disk first and then use this library to play it.

**Comment by pheromone** [comment]
thank you.
