### ISSUE TITLE
Audio & Video Player stop working after using Audio Recorder on iOS

### ISSUE THREAD

**Issue by ER1011** [jsierles/react-native-audio#173]
iOS 10
react 15.4.2
react-native 0.41.2
react-native-audio 3.2.1   (to record audio messages)
react-native-camera 0.6.0   (to record videos)
react-native-video 1.0.0   (to play videos)
react-native-sound 0.9.1   (to play audio messages)

After using react-native-audio to record audio, both the audio player and video player stop working. Specifically, when we call "play" on the player it returns a false. The issue is systematic.

After researching the issue, I found [this](http://stackoverflow.com/questions/13618810/avaudioplayer-play-returns-false-on-hardware). 

They suggest replacing:
**[[AVAudioSession sharedInstance] setActive: NO error: nil];**
with:
**[[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayback error: nil];**
after stopping audio recording. 

I did make the change in AudioRecorderManager.m and it did fix the issue. Has anybody had this issue and is this indeed the proper way to solve it? I'm concerned if nobody has had this issue using react-native-audio then the root cause of my problem is somewhere else in our code.

thank you so much! And thank you for the great plugin!

**Comment by brunsy** [comment]
Also having this problem on IOS 10.
Making the same change fixed it for me.
