### ISSUE TITLE
Possible data visualization

### ISSUE THREAD

**Issue by tgoldenberg** [jsierles/react-native-audio#18]
This is probably out of the scope of this project, but how would I get a data visualization of the recorded audio, or audio that is preloaded into the project and played via the `AudioPlayer`? I have created a SO question [here](http://stackoverflow.com/questions/33194943/react-native-audio-visualization?noredirect=1#comment54196027_33194943). Any suggestions would be very welcome. If it isn't within the scope of the project feel free to close the issue. Thank you :)

**Comment by jsierles** [comment]
The recommendations on SO are good ones - EZAudio is a solid package with a few variations in the visualization theme. Using gl-react-native or react-art to draw it yourself is possible too. This module would need to expose one more value: the current metering level during recording.

I'd recommend first thinking about what you need - a scrollable visualization? eye candy? will the user need to interact with it?

Using EZAudio you'd have to build your own native bridge: this module would not be that useful.

Of course I'd love to work on these problems, but right now I'm on other projects and not actively using this module.

Hope this helps!

**Comment by tgoldenberg** [comment]
@jsierles Thank you! I would consider paying someone to write a wrapper for EZAudio - it is so essential to what I want to do, and I don't have any experience working with native modules, though I certainly can try. I would definitely need access to the FFT values of the recorded and loaded sounds - that would be essential to comparing two recorded words and testing the accuracy of the pronunciation. 

I hope that the Universe will give you some free time to help with this challenge :). Thank you for the help!

**Comment by juananime** [comment]
Hi I started a React Native component specifically focused in audio visualisation. You may like have a look in https://github.com/juananime/react-native-audiowaveform
Or try straight away npm react-native-audiowaveform --save
Cheers
