### ISSUE TITLE
AudioRecordManager.checkAuthorizationStatus undefined on iOS while working perfectly on Android

### ISSUE THREAD

**Issue by cfournel** [jsierles/react-native-audio#182]
react-native-audio :  3.2.2
react-native : 0.44
react :  16.0.0-alpha.6
using react-native-sound ? Yes

### Expected behaviour :

Just using the example which is working on Android marshmallow and not on iOS 10.3 (simulator) and 10.2 ( iphone 6s )

### Actual behaviour

showing the RSOD ( Red Screen Of Death ) 
![capture du 2017-05-27 22-27-52](https://cloud.githubusercontent.com/assets/6419077/26524200/c611380c-432b-11e7-991c-8f5047507063.png)

### Steps to reproduce

- del all watchman stuff
- rm -rf node_modules dir
- npm install
- react-native link ( just to be sure everything is already linked )
- npm start --reset-cache
- react-native run-ios 

( i can confirm this is perfectly working on android )

**Comment by Noitidart** [comment]
This is an aside, I saw you were able to get this to work on Android. Some of us are hitting "Start Failed", did you encounter this issue? It would be awesome if you could chime in if you know, if possible, sharing your code would help a lot! - github.com/jsierles/react-native-audio/issues/177

**Comment by cfournel** [comment]
Yes I did met the start failed issue !
Unfortunatly I m not sure how I solved it ( was 6 or 7 days ago),  I started my app from the audio example from the module

**Comment by Noitidart** [comment]
Haha! That is sooo funny thanks for sharing that! :) I will keep trying at it. :)

**Comment by cfournel** [comment]
@Noitidart  Did you had permissionb for microphone in your androidManifest.xml ?

**Comment by Noitidart** [comment]
Yes sir I did, thanks sooo much for asking! I was struggling with this for days!

Here is screenshot of my manifest:

![](http://i.imgur.com/cpwk4Nd.png)

**Comment by cfournel** [comment]
@Noitidart  here is a gist of my code https://gist.github.com/cfournel/8700de7ed9740562fc97e8e81584e62f

**Comment by Noitidart** [comment]
Thank you so much I will study it now!

**Comment by cfournel** [comment]
@jsierles  : i finally found my issue , seems like audio librairies wasnt in the "link binary with libraries"
