### ISSUE TITLE
Could you please add a .podspec

### ISSUE THREAD

**Issue by del-naz** [jsierles/react-native-audio#190]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  3.2.2
react-native : 0.44.2
react :  16.0.0-alpha.6
using react-native-sound ? Yes/No
Yes

### Expected behaviour 

Expected to have a 'react-native-audio.podspec' file so the library can be linked using cocopods

What were you trying to do and what did you expect to happen ?

Link the react-native-audio to an existing IOS app using Cocoapods

### Actual behaviour

.podspec file was not included

What happened when your issue occurred ? The more details you provide here the better the odds are that someone will help you resolve your issue

I had to manually add a .podspec file as follows. It would help if you add this to the master.

require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-audio"
  s.version      = package["version"]
  s.summary      = "A <Audio /> element for react-native"
  s.author       = "Joshua Sierles <joshua@diluvia.net> (https://github.com/jsierles)",

  s.homepage     = "https://github.com/jsierles/react-native-audio"

  s.license      = "MIT"
  s.platform     = :ios, "7.0"

  s.source       = { :git => "https://github.com/jsierles/react-native-audio.git", :tag => "#{s.version}" }

  s.source_files  = "ios/*.{h,m}"

  s.dependency "React"
end

### Steps to reproduce

Please provide us with some code that we can run to reproduce your error. 

### Link to a git repo that reproduces bug 

If you put a GitHub repo that reproduces your issue then you significantly increase your chances of getting help !

**Comment by joshbax** [comment]
I made one. Here you go:
```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name                = "RNAudio"
  s.version             = package['version']
  s.summary             = package['description']
  s.homepage            = "https://github.com/jsierles/react-native-audio"
  s.license             = package['license']
  s.author              = package['author']
  s.source              = { :git => package['repository']['url'], :tag => "v#{s.version}" }
  s.default_subspec     = 'Core'
  s.requires_arc        = true
  s.platform            = :ios, "9.0"
  
  s.dependency 'React/Core'
  
  s.subspec 'Core' do |ss|
    ss.source_files     = "ios/*.{h,m,swift}"
  end

end
```

**Comment by jsierles** [comment]
Already done.
