### ISSUE TITLE
No way to unpause AudioPlayer

### ISSUE THREAD

**Issue by getsetbro** [jsierles/react-native-audio#20]
Seems there is no unpause because clicking play starts from the beginning and clicking pause again does nothing.

**Comment by jsierles** [comment]
This is true in the example, but calling play() or playRecording() after pausing should work. Let me know if it doesn't!

**Comment by getsetbro** [comment]
I am using AudioPlayer.pause() with mp3s. Then AudioPlayer.play(); does nothing and AudioPlayer.play(path); starts a song at the beginning.

**Comment by jsierles** [comment]
OK, I'll take a look at this soon!

**Comment by tgoldenberg** [comment]
+1 I also just noticed this

**Comment by jsierles** [comment]
I'll be looking at this later today.

**Comment by LennonR** [comment]
I'm about to submit a PR that solves this problem and adds some other audio player manager functionality.

**Comment by LennonR** [comment]
pull #25 addresses this issue by adding an unpause method

**Comment by jsierles** [comment]
#25 is merged. Thanks @LennonR!
