### ISSUE TITLE
Err import this lib + react-native-sound?

### ISSUE THREAD

**Issue by thiennhank9** [jsierles/react-native-audio#201]
Hey guys, I create new project and import react-native-audio and react-native-sound.
Now I'm stuck at error while running it on Android! (Although I run AudioExample working ^^)
I attached file image! (I did npm install 2 packages and react-native link both 2)
![err](https://user-images.githubusercontent.com/18640233/29010585-8fd00bfc-7b56-11e7-98b6-db022f2aadbc.PNG)

**Comment by robertherber** [comment]
I get the same error

**Comment by napatwongchr** [comment]
#199

**Comment by napatwongchr** [comment]
@robertherber  check this #199
