### ISSUE TITLE
Record audio in 48khz, 16 bit

### ISSUE THREAD

**Issue by shayhz** [jsierles/react-native-audio#207]
Hi,

I want to develop a mobile app in react-native that record audio in 48khz, 16 bit.
I don't understand from the documentation if it's possible to do it using this package.
Can I pass SampleRate=48000? How can I make it 16 bit?

Thanks a lot !

**Comment by modularity** [comment]
You can specify the property AudioEncodingBitRate: 16000. This is only available right now for [Android](https://github.com/jsierles/react-native-audio#android-only-fields).
