### ISSUE TITLE
ReactNativeAudioPackage.java:35: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by napatwongchr** [jsierles/react-native-audio#208]
I'm trying to run react-native run-android and it got this build error

> :react-native-audio:processReleaseResources
:react-native-audio:generateReleaseSources
:react-native-audio:incrementalReleaseJavaCompilationSafeguard
:react-native-audio:compileReleaseJavaWithJavac
:react-native-audio:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/knotnapat/Project/InterviewerTool/node_modules/react-native-audio/android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:35: error: method does not override or implement a method from a supertype
@Override
 ^
1 error
:react-native-audio:compileReleaseJavaWithJavac FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':react-native-audio:compileReleaseJavaWithJavac'.
 Compilation failed; see the compiler error output for details.

I use all these packages.
react-native-audio :  3.2.2
react-native : 0.47.2
react :  16.0.0-alpha.12
using react-native-sound ?: No

**Comment by napatwongchr** [comment]
Ok i found the problem. It is react-native 0.47 breaking changes. It removed createJSModule.

**Comment by gavin-gmlab** [comment]
How to fix this? I am also trying to move to RN 0.47

**Comment by napatwongchr** [comment]
@gavin-gmlab i've commented this line of code from ReactnativeAudioPackage.java
`// @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }`
Since RN 0.47 has removed this method so it can't override.

**Comment by febeling** [comment]
@napatwongchr Why did you close the issue? It seems to persist for version 0.47.

**Comment by febeling** [comment]
Duplicate of #198.

**Comment by zhenizhui** [comment]
Duplicate of https://github.com/jsierles/react-native-audio/issues/240

**Comment by zhenizhui** [comment]
react-native@0.41.2 seems has the same problem, suddenly.

I didn't got this error a few weeks ago while today I get it.
