### ISSUE TITLE
No valid audio data received. You may be using a device that can't record audio.

### ISSUE THREAD

**Issue by huanghaodong** [jsierles/react-native-audio#209]
No valid audio data received. You may be using a device that can't record audio.
<unknown>
    C:\Users\Admin\Documents\IM\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57
__invokeCallback
    C:\Users\Admin\Documents\IM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:354:19
<unknown>
    C:\Users\Admin\Documents\IM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:129:28
__guard
    C:\Users\Admin\Documents\IM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:269:6
invokeCallbackAndReturnFlushedQueue
    C:\Users\Admin\Documents\IM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:128:17

**Comment by jsierles** [comment]
Please provide more details - closing for now

**Comment by peakyDicers** [comment]
I came across this issue when calling the recording and then the stop recording functions too quickly on android. 

In my application, I have a button where you press down to record, and release to stop recording. If you tap too quickly, this occurs. Does not happen on IOS.

**Comment by hiennguyen92** [comment]
I have the same issue with you. Do not know if there is a solution?

**Comment by peakyDicers** [comment]
I ended up using setTimeout, so that it waits a minimum of 100 ms, before the `stop recording` function can be called.

**Comment by trinadhkoya** [comment]
Does it work for iOS simulator?

**Comment by chowdaryswathi14** [comment]
Any solution for this?

**Comment by minhtet-BeeComTech** [comment]
Any solution for this?
