### ISSUE TITLE
Possible to play 2 files at once?

### ISSUE THREAD

**Issue by getsetbro** [jsierles/react-native-audio#21]
I'd like to fade in one song during fade out of the last.

**Comment by jsierles** [comment]
Not in its current state,  This could be remedied by converting the audio player to an actual react component. It's on my list, but haven't had time to do it yet!

**Comment by getsetbro** [comment]
Another question, is this capable of changing the volume while playing files?

**Comment by getsetbro** [comment]
Also is changing the volume a possibility?

**Comment by getsetbro** [comment]
If you can point me to how to make it a react component I could work on it.

**Comment by jsierles** [comment]
I recommend following the code for react-native-video which had similar requirements.

https://github.com/brentvatne/react-native-video/blob/master/Video.ios.js
