### ISSUE TITLE
Cannot record sound on iOS, file path in undefined

### ISSUE THREAD

**Issue by Gaellan** [jsierles/react-native-audio#214]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  ^3.2.2
react-native : ^0.46.4
react :  16.0.0-alpha.12
using react-native-sound ? Yes : ^0.10.4

### Expected behaviour :

I was trying to record audio on iOS (it works perfectly on Android) and was expecting the app to ask me if it is allowed to use the microphone and then start recording.

### Actual behaviour

I did set up the appropriate permissions on the info.plist file.

When I start the recording the app does not ask me for microphone permission. When I try to print the file path, it comes out as undefined. After that when i stop the recording, and print the file path it still comes out as "undefined". I tried both on an iOS simulator and a real device (iPhone 6S : iOS 10.2) the results are the same. The code works fine on an Android device though.

### Steps to reproduce

`class RecordAudio extends Component {

    constructor(props) {
        super(props);
        this.state = {recording : false, file : null};
    }

    componentDidMount()
    {
        let filename = AudioUtils.DocumentDirectoryPath + '/sparkplant' + Date.now() + '.aac';
        this.prepareRecordingPath(filename);
    }

    prepareRecordingPath(audioPath)
    {
        AudioRecorder.prepareRecordingAtPath(audioPath, {
            SampleRate: 22050,
            Channels: 1,
            AudioQuality: "Low",
            AudioEncoding: "aac",
            AudioEncodingBitRate: 32000
        });
    }

    async record()
    {
        this.setState({recording : true});

        try {
            const filePath = await AudioRecorder.startRecording();
            console.warn(filePath);
        }
        catch(error)
        {
            console.warn(error);
        }
    }

    async stop()
    {
        this.setState({recording : false});
        let mode = this.props.tags.toRecord;

        try{
            const filePath = await AudioRecorder.stopRecording();
            console.warn(filePath);

            if(mode === "place")
            {
                this.props.tryTagsUploadPlaceAudio(this.props.login, {
                    uri: "file://" + filePath,
                    type: "audio/aac",
                    name: filePath.substring(filePath.lastIndexOf("/"))
                });
            }
            else
            {
                this.props.tryTagsUploadDescriptionAudio(this.props.login, {
                    uri: "file://" + filePath,
                    type: "audio/aac",
                    name: filePath.substring(filePath.lastIndexOf("/"))
                });
            }
        }
        catch(error)
        {
            console.warn(error);
        }
    }` 

I cannot set up a public github with the full code, but I'll be happy to add anything you might need to know :)

**Comment by beeremy** [comment]
+1

**Comment by fredbt** [comment]
hello @Gaellan we are having the same problem here in IOS (failing both in the emulator AND device). Did you find a solution?

**Comment by ufolux** [comment]
+1

**Comment by beeremy** [comment]
@ufolux thanks a lot for your answer, it works!

**Comment by Gaellan** [comment]
@ufolux thanks a lot :)

**Comment by MalikHezretov** [comment]
@jsierles I am using react-native-audio example code you  provided on github and when I try to run the example app it gives me TypeError: undefined is not a function(evaluating'_reactNativeAudio.AudioRecorder.requestAuthorization()') Error. I think requestAuthorization command is not working. My react native version is

RN 0.55.4
react-native-audio latest version


![screenshot_1536295657](https://user-images.githubusercontent.com/24701916/45199295-887d2780-b288-11e8-9600-57e119344641.png)

**Comment by rahulbhankar786** [comment]
AudioRecorder.onFinished = (data) => {
            // Android callback comes in the form of a promise instead.
            if (Platform.OS === 'ios') {
                console.log('filePath', data)
            }
          };
