### ISSUE TITLE
index.ios.bundle:14133 Cannot read property 'checkAuthorizationStatus' of undefined  index.ios.bundle:14133 Module AppRegistry is not a registered callable module (calling runApplication) handleException @ index.ios.bundle:14133 handleError @ index.ios.bundle:14805 reportFatalError @ index.ios.bundle:691 __guard @ index.ios.bundle:6238 MessageQueue.callFunctionReturnFlushedQueue @ index.ios.bundle:6080 (anonymous) @ debuggerWorker.js:72 index.ios.bundle:14141 Unhandled JS Exception: Cannot read property 'checkAuthorizationStatus' of undefined reactConsoleErrorHandler @ index.ios.bundle:14141 logToConsole @ index.ios.bundle:18274 logIfNoNativeHook @ index.ios.bundle:18257 __callFunction @ index.ios.bundle:6265 (anonymous) @ index.ios.bundle:6081 __guard @ index.ios.bundle:6236 MessageQueue.callFunctionReturnFlushedQueue @ index.ios.bundle:6080 (anonymous) @ debuggerWorker.js:72 index.ios.bundle:14141 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by HLDY** [jsierles/react-native-audio#217]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  
react-native :
react :  
using react-native-sound ? Yes/No

### Expected behaviour :

What were you trying to do and what did you expect to happen ?

### Actual behaviour

What happened when your issue occurred ? The more details you provide here the better the odds are that someone will help you resolve your issue

### Steps to reproduce

Please provide us with some code that we can run to reproduce your error. 

### Link to a git repo that reproduces bug 

If you put a GitHub repo that reproduces your issue then you significantly increase your chances of getting help !

**Comment by jsierles** [comment]
You have you link the library to your project.

**Comment by gurmukhp** [comment]
I have the same problem and have linked multiple times. Are there instructions for manually linking on iOS, I can only see on Android.

Thanks

**Comment by escobar5** [comment]
Link does not work for iOS, also there are no iOS manual instructions
