### ISSUE TITLE
Stop any and all audio

### ISSUE THREAD

**Issue by tgoldenberg** [jsierles/react-native-audio#22]
So I don't how common a circumstance this is, but in my flashcard app, each card has an audio file. If I hit play on one (and some of these are long files), then change my navigation and then return, it doesn't let me cut off the audio. Any suggestions?

**Comment by jsierles** [comment]
This may be a problem with your component unmounting, so it loses the reference to the native module and ends up creating a new one. Probably you'll have to ensure that you keep a reference to this instance of the audio player somewhere, or ensure that when unmounting, the audio is stopped. Could you make a small test case for this?

**Comment by tgoldenberg** [comment]
Hi @jsierles  

I can work on a test case, but this is what I have so far - [link](https://gist.github.com/tgoldenberg/0699dad67bd8d3a31dcd)

**Comment by franzejr** [comment]
@tgoldenberg do you have a good solution for that ? I would like to stop all the audios, It seems it does not have the same behavior on Android.
