### ISSUE TITLE
How do you manage file in Android?

### ISSUE THREAD

**Issue by popo63301** [jsierles/react-native-audio#221]
Hi everybody! I really struggle to manage the res/raw folder in Android. I need to list all the files that is inside the folder, download file to it, and also delete files. React-native-fs is a complete mess, I can't figure out how to make it work. Any ideas?

**Comment by ProteanDev** [comment]
how is React-native-fs a mess?
Did you follow the instructions on how to use it properly?

**Comment by popo63301** [comment]
Sure! Though I couldn't access the MAIN BUNDLE because it's a js bundle instead of a folder.
