### ISSUE TITLE
is there any way convert absolutepath to android content schema ?

### ISSUE THREAD

**Issue by humengqiao** [jsierles/react-native-audio#223]
because i need to upload record file , but only can pass android content schema, pass absolute path directly i get error, if there are any solutions, i will be grateful ..

**Comment by humengqiao** [comment]
I'm stuck in it

**Comment by niocncn** [comment]
did you solve issue?

**Comment by humengqiao** [comment]
hi，i use another way to resolve，you can append file schema on path depend your platform，then you can access it，and upload
![image](https://user-images.githubusercontent.com/23610300/43825143-94936080-9b26-11e8-93a8-11d17894675d.png)
