### ISSUE TITLE
AudioExamples not working

### ISSUE THREAD

**Issue by iroshanAV** [jsierles/react-native-audio#227]
## Version
react-native-cli: 2.0.1
react-native: 0.40.0
using react-native-sound ? Yes

### Expected behaviour :
AudioExamples to work
### Actual behaviour
AudioExamples not get deployed, because of an unhandled promise rejection error

![screenshot 117](https://user-images.githubusercontent.com/16167479/34316262-5ebcaf3e-e7b7-11e7-9467-89af236afcda.png)

**Comment by bqkhiem96** [comment]
As the console suggested, you're missing the Build Tools revision 23.0.2, the following tools can be installed via Android SDK

**Comment by bqkhiem96** [comment]
![image](https://user-images.githubusercontent.com/17524678/34369271-0b21376c-eaed-11e7-9360-9c5e348de00d.png)

**Comment by iroshanAV** [comment]
@bqkhiem96 well, i installed it, but error is the same

**Comment by jsierles** [comment]
The latest version requires RN >= 0.47.2. I'll update the docs to reflect that. Use a previous version if your RN version is lower.

**Comment by Biplovkumar** [comment]
thanku sir.

Thanks & Regards.
Biplov kumar

Student
Mca
Vivekananda Institute of Professional Studies
<https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiv8qXam_nLAhVWC44KHT3AA1cQFggcMAA&url=http%3A%2F%2Fwww.vips.edu%2F&usg=AFQjCNEKnNl-jafsVVUbN7tTK-CWiPRlFQ&sig2=lUiba0eZIFSPdVFZWg5Z5g&bvm=bv.118443451,d.c2E>
New Delhi, IndiaMob: +91-9835773216

Email:biplovkumar.kumar@gmail.com
Email:biplov@algofocus.com
