### ISSUE TITLE
Playback of .mp3 files supported? Volume supported?

### ISSUE THREAD

**Issue by klausbreyer** [jsierles/react-native-audio#24]
Hey!

I just wanna ask, if I can use this module to just play pure mp3 files of my own? This is not obvious through the example, because you just play your recordings there. 

Next question: Is there some kind of volume control?

thanks for your answers!

Cheers, 
Klaus

**Comment by jsierles** [comment]
You can pass a full native path to AudioPlayer.play(path) to play your Mp3 files. Volume control is not supported right now.
