### ISSUE TITLE
ReactNativeAudioPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by jackyang1984** [jsierles/react-native-audio#240]
android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java

add some codes

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

**Comment by peakyDicers** [comment]
This worked for me.

**Comment by zhenizhui** [comment]
same issue https://github.com/jsierles/react-native-audio/issues/208

**Comment by jsierles** [comment]
See the README:

> For React Native >= 0.47.2, use v3.4.0 and up. For React Native >= 0.40, use v3.1.0 up til 3.2.2. For React Native <= 0.39, use v3.0.0 or lower.
