### ISSUE TITLE
react-native@0.41.2 error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by zhenizhui** [jsierles/react-native-audio#255]
## Version
react-native@0.41.2
react-native-audio@3.2.2

Windown 10

### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  @3.2.2
react-native : @0.41.2
react :  @15.4.2
using react-native-sound ? Yes. @0.9.1

### Expected behaviour :

NO ERROR. 

I've never seen this mistake before. But today I get it.

I've read the similar issue too. But my react-native version is 0.41.2, not 0.47 above

### Actual behaviour

```
:react-native-audio:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\ZZH-WorkingSpace\deviceApp\node_modules\react-native-audio\android\src\main\java\com\rnim\rn\audio\ReactNativeAudioPackage.java:35: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误
:react-native-audio:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-audio:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 0.629 secs
```

### Steps to reproduce

"react-native-audio": "^3.2.2",

```
npm i
```

**Comment by zhenizhui** [comment]
I think it's strange 🤒

**Comment by apurvaaggarwal** [comment]
I am also facing same issue

**Comment by apurvaaggarwal** [comment]
I upgraded my react-native version to 0.53.0(react-native version of repository)  and it is solved

**Comment by zhenizhui** [comment]
@apurvaaggarwal i think it is impossible to update the react-native version because of the huge work and lots of time to update the dependencies. 😢 

But I find that there is no problem on my macbookAir. 

And certainly, i won' t update the dependencies on the mac.

**Comment by rezydent** [comment]
@zhenizhui 
in /android/build.gradle add
```
subprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:0.43.1'
        }
    }
}
```
Change to whatever RN version you are using

**Comment by zhenizhui** [comment]
@rezydent thank you! 😄 

But I want to know how it happen. I don't need to add the code you provided and it worked well several weeks ago.

Very much appreciated again!

**Comment by rezydent** [comment]
@zhenizhui I think it was on Bintray, but now it's gone (too bad because the reviews for it were hilarious). Someone simply made it public instead of private by accident.

**Comment by zhenizhui** [comment]
@rezydent 

ok, thank you for your answer 👍
