### ISSUE TITLE
Audio file mime type on android only

### ISSUE THREAD

**Issue by Macromeda** [jsierles/react-native-audio#264]
## Version
react-native-audio :  4.1.3
react-native : 0.55.4
react :  16.3.1
using react-native-sound ? Yes

## Expected behaviour :
Expecting that the mime type of the recorded audio file to be an **audio mime type**.

## Actual behaviour
Mime type that I detect is **'video/mp4'**, What really causes the trouble is when I upload the file to a server that reads the mime type to take the proper action.

## Steps to reproduce
This only happens on android devices, on IOS it works just fine.
When I use the library react-native-sound, it detects the audio and it works, the problem happens when I try to upload the file, because of the mime type as i mentioned above.

```
AudioRecorder.prepareRecordingAtPath(audioPath, {
	SampleRate: 22050,
	Channels: 1,
	AudioQuality: 'Low',
	AudioEncoding: 'aac',
	AudioEncodingBitRate: 32000
});
```

**Comment by MinaFSedrak** [comment]
+1

**Comment by Macromeda** [comment]
Turns out the the server was using a tool that gets confused between aac for mp4 and aac for audio.
this [article](https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/SupportedAudioFormatsMacOSX/SupportedAudioFormatsMacOSX.html ) explains it all.
