### ISSUE TITLE
Record file with 0 bytes

### ISSUE THREAD

**Issue by expouic** [jsierles/react-native-audio#273]
react-native-audio :  4.1.3
react-native : 0.55.4
react : 16.4.0
using react-native-sound ? No

Trying to record audio file but the end file stay with 0 bytes

adb grep
>  ReactNativeJS: Finished recording of duration 6 seconds at path: /data/user/0/myAPP/files/test.aac and size of 0 bytes

AudioRecorder.onProgress = (data) => {
     console.log(data.currentMetering, data.currentPeakMetering)
};

> ReactNativeJS: undefined, undefined

**Comment by chinnr** [comment]
using stat(path) by react-native-fs

**Comment by oguzkaganeren** [comment]
`AudioRecorder.onProgress = (data) => {
console.log(data.currentMetering, data.currentPeakMetering)
};` 

> ReactNativeJS: undefined, undefined
I get same problem, how can I fix it?

**Comment by expouic** [comment]
On this my example, i'm using and changing code from [AudioExample](https://github.com/jsierles/react-native-audio/tree/master/AudioExample) adding option to upload record file to server

**Dependences:**
npm i axios


`import React, {Component} from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  Platform,
  PermissionsAndroid,
} from 'react-native';
import axios from 'axios';
import Sound from 'react-native-sound';
import {AudioRecorder, AudioUtils} from 'react-native-audio';

class AudioExample extends Component {

    state = {
      currentTime: 0.0,
      recording: false,
      paused: false,
      stoppedRecording: false,
      finished: false,
      audioPath: AudioUtils.DocumentDirectoryPath + '/test.aac',
      hasPermission: undefined,
    };

    prepareRecordingPath(audioPath){
      AudioRecorder.prepareRecordingAtPath(audioPath, {
        SampleRate: 22050,
        Channels: 1,
        AudioQuality: "Low",
        AudioEncoding: "aac",
        AudioEncodingBitRate: 32000
      });
    }

    componentDidMount() {
      this._checkPermission().then((hasPermission) => {
        this.setState({ hasPermission });

        if (!hasPermission) return;

        this.prepareRecordingPath(this.state.audioPath);

        AudioRecorder.onProgress = (data) => {
          this.setState({currentTime: Math.floor(data.currentTime)});
        };

        AudioRecorder.onFinished = (data) => {
          // Android callback comes in the form of a promise instead.
          if (Platform.OS === 'ios') {
            this._finishRecording(data.status === "OK", data.audioFileURL, data.audioFileSize);
          }
        };
      });
    }

    _checkPermission() {
      if (Platform.OS !== 'android') {
        return Promise.resolve(true);
      }

      const rationale = {
        'title': 'Microphone Permission',
        'message': 'AudioExample needs access to your microphone so you can record audio.'
      };

      return PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, rationale)
        .then((result) => {
          console.log('Permission result:', result);
          return (result === true || result === PermissionsAndroid.RESULTS.GRANTED);
        });
    }

    _renderButton(title, onPress, active) {
      var style = (active) ? styles.activeButtonText : styles.buttonText;

      return (
        <TouchableHighlight style={styles.button} onPress={onPress}>
          <Text style={style}>
            {title}
          </Text>
        </TouchableHighlight>
      );
    }

    _renderPauseButton(onPress, active) {
      var style = (active) ? styles.activeButtonText : styles.buttonText;
      var title = this.state.paused ? "RESUME" : "PAUSE";
      return (
        <TouchableHighlight style={styles.button} onPress={onPress}>
          <Text style={style}>
            {title}
          </Text>
        </TouchableHighlight>
      );
    }

    async _pause() {
      if (!this.state.recording) {
        console.warn('Can\'t pause, not recording!');
        return;
      }

      try {
        const filePath = await AudioRecorder.pauseRecording();
        this.setState({paused: true});
      } catch (error) {
        console.error(error);
      }
    }

    async _resume() {
      if (!this.state.paused) {
        console.warn('Can\'t resume, not paused!');
        return;
      }

      try {
        await AudioRecorder.resumeRecording();
        this.setState({paused: false});
      } catch (error) {
        console.error(error);
      }
    }

    async _stop() {
      if (!this.state.recording) {
        console.warn('Can\'t stop, not recording!');
        return;
      }

      this.setState({stoppedRecording: true, recording: false, paused: false});

      try {
        const filePath = await AudioRecorder.stopRecording();

        if (Platform.OS === 'android') {
          this._finishRecording(true, filePath);
        }
        return filePath;
      } catch (error) {
        console.error(error);
      }
    }

    async _play() {
      if (this.state.recording) {
        await this._stop();
      }

      // These timeouts are a hacky workaround for some issues with react-native-sound.
      // See https://github.com/zmxv/react-native-sound/issues/89.
      setTimeout(() => {
        var sound = new Sound(this.state.audioPath, '', (error) => {
          if (error) {
            console.log('failed to load the sound', error);
          }
        });

        setTimeout(() => {
          sound.play((success) => {
            if (success) {
              console.log('successfully finished playing');
            } else {
              console.log('playback failed due to audio decoding errors');
            }
          });
        }, 100);
      }, 100);
    }

    async _record() {
      if (this.state.recording) {
        console.warn('Already recording!');
        return;
      }

      if (!this.state.hasPermission) {
        console.warn('Can\'t record, no permission granted!');
        return;
      }

      if(this.state.stoppedRecording){
        this.prepareRecordingPath(this.state.audioPath);
      }

      this.setState({recording: true, paused: false});

      try {
        const filePath = await AudioRecorder.startRecording();
      } catch (error) {
        console.error(error);
      }
    }

    _finishRecording(didSucceed, filePath) {
      this.setState({ finished: didSucceed });
      console.log(`Finished recording of duration ${this.state.currentTime} seconds at path: ${filePath}`);

        let ext = 'aac';
        let data = new FormData();
        data.append('file', {
            uri:`file://${filePath}`,
            name:`recording.${ext}`,
            type:`audio/${ext}`
        });

        //Upload file to server
        const url = "YOUR_END_POINT";
        let headers = {};
        headers['Content-Type'] = 'multipart/form-data;';

        axios.post(url, data, {headers:headers});
    }

    render() {

      return (
        <View style={styles.container}>
          <View style={styles.controls}>
            {this._renderButton("RECORD", () => {this._record()}, this.state.recording )}
            {this._renderButton("PLAY", () => {this._play()} )}
            {this._renderButton("STOP", () => {this._stop()} )}
            {/* {this._renderButton("PAUSE", () => {this._pause()} )} */}
            {this._renderPauseButton(() => {this.state.paused ? this._resume() : this._pause()})}
            <Text style={styles.progressText}>{this.state.currentTime}s</Text>
          </View>
        </View>
      );
    }
  }

  var styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#2b608a",
    },
    controls: {
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
    },
    progressText: {
      paddingTop: 50,
      fontSize: 50,
      color: "#fff"
    },
    button: {
      padding: 20
    },
    disabledButtonText: {
      color: '#eee'
    },
    buttonText: {
      fontSize: 20,
      color: "#fff"
    },
    activeButtonText: {
      fontSize: 20,
      color: "#B81F00"
    }

  });

export default AudioExample;
`

**Comment by tmjordan** [comment]
@expouic please man, how do you make recording work on iOS? dit you use stat(path)? I'm stuck on that problem for too long

**Comment by alainib** [comment]
any fix for this problem please ?

**Comment by BdN3504** [comment]
> any fix for this problem please ?

The android method AudioRecorder.stopRecording only returns the file path of the file that was written, it does not return a data structure containing the file size. The ios implementation does return the file size. So if you see a message in your console that is telling you that 0 bytes have been recorded, that message is wrong. 

As mentioned here
> using stat(path) by react-native-fs
you can use this method to retrieve the file size. Provide the file path returned by the stopRecording method to stat as the parameter.

**Comment by Praveensahu365** [comment]
How to send audioPath by json data

**Comment by Praveensahu365** [comment]
> On this my example, i'm using and changing code from [AudioExample](https://github.com/jsierles/react-native-audio/tree/master/AudioExample) adding option to upload record file to server
> 
> **Dependences:**
> npm i axios
> 
> `import React, {Component} from 'react';
> import {
> AppRegistry,
> StyleSheet,
> Text,
> View,
> TouchableHighlight,
> Platform,
> PermissionsAndroid,
> } from 'react-native';
> import axios from 'axios';
> import Sound from 'react-native-sound';
> import {AudioRecorder, AudioUtils} from 'react-native-audio';
> 
> class AudioExample extends Component {
> 
> ```
> state = {
>   currentTime: 0.0,
>   recording: false,
>   paused: false,
>   stoppedRecording: false,
>   finished: false,
>   audioPath: AudioUtils.DocumentDirectoryPath + '/test.aac',
>   hasPermission: undefined,
> };
> 
> prepareRecordingPath(audioPath){
>   AudioRecorder.prepareRecordingAtPath(audioPath, {
>     SampleRate: 22050,
>     Channels: 1,
>     AudioQuality: "Low",
>     AudioEncoding: "aac",
>     AudioEncodingBitRate: 32000
>   });
> }
> 
> componentDidMount() {
>   this._checkPermission().then((hasPermission) => {
>     this.setState({ hasPermission });
> 
>     if (!hasPermission) return;
> 
>     this.prepareRecordingPath(this.state.audioPath);
> 
>     AudioRecorder.onProgress = (data) => {
>       this.setState({currentTime: Math.floor(data.currentTime)});
>     };
> 
>     AudioRecorder.onFinished = (data) => {
>       // Android callback comes in the form of a promise instead.
>       if (Platform.OS === 'ios') {
>         this._finishRecording(data.status === "OK", data.audioFileURL, data.audioFileSize);
>       }
>     };
>   });
> }
> 
> _checkPermission() {
>   if (Platform.OS !== 'android') {
>     return Promise.resolve(true);
>   }
> 
>   const rationale = {
>     'title': 'Microphone Permission',
>     'message': 'AudioExample needs access to your microphone so you can record audio.'
>   };
> 
>   return PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, rationale)
>     .then((result) => {
>       console.log('Permission result:', result);
>       return (result === true || result === PermissionsAndroid.RESULTS.GRANTED);
>     });
> }
> 
> _renderButton(title, onPress, active) {
>   var style = (active) ? styles.activeButtonText : styles.buttonText;
> 
>   return (
>     <TouchableHighlight style={styles.button} onPress={onPress}>
>       <Text style={style}>
>         {title}
>       </Text>
>     </TouchableHighlight>
>   );
> }
> 
> _renderPauseButton(onPress, active) {
>   var style = (active) ? styles.activeButtonText : styles.buttonText;
>   var title = this.state.paused ? "RESUME" : "PAUSE";
>   return (
>     <TouchableHighlight style={styles.button} onPress={onPress}>
>       <Text style={style}>
>         {title}
>       </Text>
>     </TouchableHighlight>
>   );
> }
> 
> async _pause() {
>   if (!this.state.recording) {
>     console.warn('Can\'t pause, not recording!');
>     return;
>   }
> 
>   try {
>     const filePath = await AudioRecorder.pauseRecording();
>     this.setState({paused: true});
>   } catch (error) {
>     console.error(error);
>   }
> }
> 
> async _resume() {
>   if (!this.state.paused) {
>     console.warn('Can\'t resume, not paused!');
>     return;
>   }
> 
>   try {
>     await AudioRecorder.resumeRecording();
>     this.setState({paused: false});
>   } catch (error) {
>     console.error(error);
>   }
> }
> 
> async _stop() {
>   if (!this.state.recording) {
>     console.warn('Can\'t stop, not recording!');
>     return;
>   }
> 
>   this.setState({stoppedRecording: true, recording: false, paused: false});
> 
>   try {
>     const filePath = await AudioRecorder.stopRecording();
> 
>     if (Platform.OS === 'android') {
>       this._finishRecording(true, filePath);
>     }
>     return filePath;
>   } catch (error) {
>     console.error(error);
>   }
> }
> 
> async _play() {
>   if (this.state.recording) {
>     await this._stop();
>   }
> 
>   // These timeouts are a hacky workaround for some issues with react-native-sound.
>   // See https://github.com/zmxv/react-native-sound/issues/89.
>   setTimeout(() => {
>     var sound = new Sound(this.state.audioPath, '', (error) => {
>       if (error) {
>         console.log('failed to load the sound', error);
>       }
>     });
> 
>     setTimeout(() => {
>       sound.play((success) => {
>         if (success) {
>           console.log('successfully finished playing');
>         } else {
>           console.log('playback failed due to audio decoding errors');
>         }
>       });
>     }, 100);
>   }, 100);
> }
> 
> async _record() {
>   if (this.state.recording) {
>     console.warn('Already recording!');
>     return;
>   }
> 
>   if (!this.state.hasPermission) {
>     console.warn('Can\'t record, no permission granted!');
>     return;
>   }
> 
>   if(this.state.stoppedRecording){
>     this.prepareRecordingPath(this.state.audioPath);
>   }
> 
>   this.setState({recording: true, paused: false});
> 
>   try {
>     const filePath = await AudioRecorder.startRecording();
>   } catch (error) {
>     console.error(error);
>   }
> }
> 
> _finishRecording(didSucceed, filePath) {
>   this.setState({ finished: didSucceed });
>   console.log(`Finished recording of duration ${this.state.currentTime} seconds at path: ${filePath}`);
> 
>     let ext = 'aac';
>     let data = new FormData();
>     data.append('file', {
>         uri:`file://${filePath}`,
>         name:`recording.${ext}`,
>         type:`audio/${ext}`
>     });
> 
>     //Upload file to server
>     const url = "YOUR_END_POINT";
>     let headers = {};
>     headers['Content-Type'] = 'multipart/form-data;';
> 
>     axios.post(url, data, {headers:headers});
> }
> 
> render() {
> 
>   return (
>     <View style={styles.container}>
>       <View style={styles.controls}>
>         {this._renderButton("RECORD", () => {this._record()}, this.state.recording )}
>         {this._renderButton("PLAY", () => {this._play()} )}
>         {this._renderButton("STOP", () => {this._stop()} )}
>         {/* {this._renderButton("PAUSE", () => {this._pause()} )} */}
>         {this._renderPauseButton(() => {this.state.paused ? this._resume() : this._pause()})}
>         <Text style={styles.progressText}>{this.state.currentTime}s</Text>
>       </View>
>     </View>
>   );
> }
> ```
> 
> }
> 
> var styles = StyleSheet.create({
> container: {
> flex: 1,
> backgroundColor: "#2b608a",
> },
> controls: {
> justifyContent: 'center',
> alignItems: 'center',
> flex: 1,
> },
> progressText: {
> paddingTop: 50,
> fontSize: 50,
> color: "#fff"
> },
> button: {
> padding: 20
> },
> disabledButtonText: {
> color: '#eee'
> },
> buttonText: {
> fontSize: 20,
> color: "#fff"
> },
> activeButtonText: {
> fontSize: 20,
> color: "#B81F00"
> }
> 
> });
> 
> export default AudioExample;
> `

what if I choose content type:-application/json
