### ISSUE TITLE
I need to show waveform while recording, so how can I get the counts for the same.

### ISSUE THREAD

**Issue by Harsh2402** [jsierles/react-native-audio#290]
react-native : 0.57.0
react :  16.5.0
using react-native-sound? Yes

### Platforms:
- Android:

I need to show waveform while recording, so how can I get the counts for the same.

Can anyone help me with this?

**Comment by joshien1997** [comment]
Have you solved it ?

**Comment by Harsh2402** [comment]
@joshien1997 
I have updated my answer for this in following link, Hope it works for you. :)

https://github.com/jsierles/react-native-audio/issues/292
