### ISSUE TITLE
Sending The Record To The Backend

### ISSUE THREAD

**Issue by abdul-elah-js** [jsierles/react-native-audio#302]
### Versions

react-native-audio :  4.2.2
react-native : 0.57.5
react :  16.6.1
using react-native-sound ? Not Yet

### Expected behaviour :

I want to start recording on button press then either send or delete the voice note
exactly like Whatsapp's voice notes

### Actual behaviour

I logged the data passed to the `onFinished` method and i got the `audioFileURL` and i tried to append it to `FormData()` to send it to my backend, but i keep getting empty array on the backend, 

### Steps to reproduce

1. react-native init project
2. sails new project-server
3. yarn add react-native-audio
4. react-native link react-native-audio

in project - react-native

```

render() {
    return (
        <TouchableOpacity onPress={ this.start_timer }>
                <Icon name="microphone-outline" type="MaterialCommunityIcons" style={ styles.microphone_icon } />
         </TouchableOpacity>

        {
            this.state.is_recording

            ? <View style={ styles.recorder_container }>
                    <TouchableOpacity onPress={ this.clear_time }>
                        <Icon name="ios-trash" type="Ionicons" style={ styles.trash_icon } />
                    </TouchableOpacity>

                      <Text style={ styles.timer }>{ this.state.count_up.format('mm:ss') }</Text>

                    <TouchableOpacity onPress={ this.send }>
                        <Icon name="md-send" type="Ionicons" style={ styles.send_icon } />
                    </TouchableOpacity>
                </View>

            : null
        }
    )
}


// Functions 

start_timer = () => {

    this.setState({ is_recording: true })

    let audioPath = AudioUtils.DocumentDirectoryPath + '/test.aac';

    this.audio = AudioRecorder.prepareRecordingAtPath(audioPath, {
      SampleRate: 22050,
      Channels: 1,
      AudioQuality: "Low",
      AudioEncoding: "aac"
    });

    this.setState({ audio: audioPath })

    this.interval = setInterval(() => this.setState(prev => ({ count_up: prev.count_up.add(1, 'second') })), 1000)

  }

  send = async () => {

    await AudioRecorder.stopRecording();

    this.setState({ is_recording: false })

    AudioRecorder.onFinished = async (data) => {

      let fd = new FormData();

      await fd.append('file', data.audioFileURL)

      let sound = await Api.post('api/chats/upload-vc', fd)

    }

  }

  clear_time = () => {
    
    this.setState({ is_recording: false, count_up: moment().minute(0).second(0) })
    
    clearInterval(this.interval)
    
  }
```

Sails JS

```
upload_voice_note: async function (req, res) {

    console.log('hello');

    req.file('file').upload({ dirname: process.cwd() + '/assets/voice-notes/' }, function(err, uploaded_voice_note) {

      console.log(uploaded_voice_note);

    })
)
```

My out put in the Sails JS is empty array

```
> hello
> []
```

**Comment by abdul-elah-js** [comment]
Closing the issue, turns out i had to add an object instead of the file path alone like
`await fd.append('file', { uri: data.audioFileURL, name: 'audio.aac' })`
instead of 
`await fd.append('file', data.audioFileURL)`

**Comment by anastely** [comment]
Hey @abdul-elah-js  I want to do the same, and now when I log the `data` after finish record i got something like this

`data {"base64":"","audioFileURL":"file:///data/user/0/com.app/files/test.aac","status":"OK"}`
 I don't have a backend yet,  I will use firebase In the future , 
SO my question is **audioFileURL** , 
it's a valid URL? and will be uploaded to own backend?
