### ISSUE TITLE
[new feature recommend] how about add cancel recording function?

### ISSUE THREAD

**Issue by guopeng1994** [jsierles/react-native-audio#306]
some times we want to cancel the record operation. Now it only have start, stop, pause, resume, and don't have cancel, so if i want to cancel, i need to do something with the recorded file, like check and delete, and maybe i need to install any other libraries to handle the saved file, so i thought it may be not necessary.if this library did this it would be nice!!!

**Comment by karam89** [comment]
I really needed this feature

how to implement the cancel functionality?

**Comment by guopeng1994** [comment]
@karam89 sry. i don't know .... ... ....
