### ISSUE TITLE
Can not play audio via speaker when the device set silent

### ISSUE THREAD

**Issue by leijing7** [jsierles/react-native-audio#31]
I added below code in RCT_EXPORT_METHOD(play:(NSString *)path) to support the feature

    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];

**Comment by jsierles** [comment]
This would be a great small PR - supporting setting the AudioSession category. I'd prefer that to assuming AVAudioSessionCategoryPlayback as the default. Could you send a PR?

**Comment by jsierles** [comment]
Available now in #41.
