### ISSUE TITLE
Added encoding option to recording

### ISSUE THREAD

**Issue by wootwoot1234** [jsierles/react-native-audio#38]
I added an encoding option to recording.  I had a hard time figuring out which encoding type to use for `.caf` files.  You used a hard coded number, 16 which I think translates to kAudioFormatMPEGLayer2.  That might be worth double checking.  I tried to create a pull request but I can't figure out how to just pull this commit (https://github.com/wootwoot1234/react-native-audio/commit/43df597b48de72f7e51212321e4a67a9d78b1d11) and not all the changes in my fork.  Hope it helps.

**Comment by wootwoot1234** [comment]
Oops, and this small change too.  https://github.com/wootwoot1234/react-native-audio/commit/d85d7b33603305938a9522e3327485cf838b302a

**Comment by hartmamt** [comment]
@wootwoot1234 - awesome. yeah i just added some of the options i needed. @jsierles has asked me to support all the options.  if you want i can just create a new PR based on your additions?

**Comment by hartmamt** [comment]
Added as PR https://github.com/jsierles/react-native-audio/pull/39

**Comment by jsierles** [comment]
I'll check on this in the next few days. thanks!

**Comment by tommoor** [comment]
Looks like this has been merged already :smile:

**Comment by wootwoot1234** [comment]
It's been a while since this thread was commented on and now I'm forgetting where we left it.  

@jsierles I have a fork of the code that adds a playWithPath() method and an encoding option to change how recorded audio is encoded.  Would you mind taking a look at my code and letting me know if you would be interested in a pull request?  I'm also going to start working on a method to determine if the app has permission to use the microphone.

**Comment by jsierles** [comment]
Sure - feel free to submit a PR!

**Comment by wootwoot1234** [comment]
@jsierles after looking closer at the code, a ```playWithPath``` doesn't make sense.  We should just add the ability to play files from the documents, library and main bundle directories using ```play```.  I can think of three ways to do it. 

1. Pass a parameter to ```play``` with either "Documents", "Library", or "MainBundle".  Then the path parameter would be relative to the directory specified.

2. Instead of passing the relative path to ```play``` like we do now, pass the absolute path.  We would also supply paths to the documents, library, and main bundle directories as constants.  This is how react native fs does it here: https://github.com/johanneslumpe/react-native-fs#constants.  I like this approach best but it would be a breaking change to the code.

3. The last option I can think of is to add two more methods ```playFromDocuments``` and  ```playFromLibrary```.  We wouldn't need one for the main bundle because ```play``` handles that.

What do you think?

**Comment by jsierles** [comment]
I agree that #2 is the best option, so I'd say we go with that.

**Comment by jsierles** [comment]
Opening a new issue to track this!
