### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by mlennon3** [jsierles/react-native-audio#45]
Hi, is there an appetite for this project to support Android?

**Comment by hartmamt** [comment]
I would definitely love that.  I will be needing an Android version of this soon so I may be able to help.

**Comment by jsierles** [comment]
Closing in favor of a future PR!

**Comment by narychen** [comment]
When will it be implemented?

**Comment by jsierles** [comment]
I'm not using the component now, so someone who needs android support will have to submit a PR.

**Comment by narychen** [comment]
Everyone should use it cuz there's a lot of android around our world.

**Comment by andyhu** [comment]
Is it possible to convert this cordova plugin into react native one?
https://github.com/emj365/cordova-plugin-audio-recorder-api
If I know how to develop android app I would like to help, but I don't..
