### ISSUE TITLE
Error loading mp3, npm start

### ISSUE THREAD

**Issue by voidvoxel** [jsierles/react-native-audio#49]
```
transforming [======================================= ] 99% 539/546TypeError: unsupported file type
    at lookup (/Users/user/Dev/app/app/node_modules/image-size/lib/index.js:35:9)
    at /Users/user/Dev/app/app/node_modules/image-size/lib/index.js:93:22
    at /Users/user/Dev/app/app/node_modules/image-size/lib/index.js:50:9
    at /Users/user/Dev/app/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```
It works fine if I put my mp3 file outside the project scope (on my Desktop for instance) and I just load by '/Users/user/Desktop/abc.mp3', but when I move the mp3 file into my project, it throws this error 0_o

**Comment by jsierles** [comment]
Looks like this error is coming from another module related to images. Possible

**Comment by voidvoxel** [comment]
@jsierles How should I go about fixing this? I tried to suppress the error in image-size but that didn't help. It looks like RN is looking at every file and trying to figure out their width/height with image-size? I don't understand why that would happen since I have .mp3 extension on my file.

**Comment by voidvoxel** [comment]
@jsierles fixed it by removing .mp3 extension. Not ideal, but it works for now. All proper audio extension seems to suffer as well: wav, mp4, etc..

**Comment by jsierles** [comment]
That's odd. Can you post some example code?

**Comment by voidvoxel** [comment]
I'm just doing `AudioPlayer.play('abc.mp3')`
I created a new RN project and added an mp3 file and it works fine.
The only thing I can think of is that my project was using RN 0.19.0 and something went wrong while upgrading to 0.21.0.
