### ISSUE TITLE
Upgrading to use w/ React Native 0.4.4

### ISSUE THREAD

**Issue by chadobado** [jsierles/react-native-audio#5]
0.4.3+ has changed the way chrome debugging works.  It's now requires the new WebSockets Library.

To make the example project work:

1. Prior to running ```npm install``` in AudioExample, update the example's package.json to (``` "react-native": "^0.4.4"```)
2. Run ```npm install```
3. Remove RCTWebSocketDebugger.xcodeproj from your project
4. Add WebSocket library from node_modules/react-native/Libraries/WebSocket/*.xcodeproj
5. Link the libRCTWebSocket.a to your project ("Link Binary with Libraries" under your project's "Build Phases").

Hope this helps someone.

**Comment by jsierles** [comment]
This has been fixed.
