### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by voidvoxel** [jsierles/react-native-audio#53]
I needed to loop an audio file so I just added `[_audioPlayer setNumberOfLoops:-1]`.
Should I PR 'loop' as an optional argument to play and playWithUrl?

**Comment by jsierles** [comment]
Sounds good - though I think it would make sense to be able to also set a `numberOfLoops` value if you don't want it to loop forever.

**Comment by voidvoxel** [comment]
Cool, yeah I meant it would take a NSNumber, not BOOL
