### ISSUE TITLE
Audio playback loading error

### ISSUE THREAD

**Issue by chadobado** [jsierles/react-native-audio#6]
Thanks for taking the time to make this, unfortunately I haven't been able to get it to work.

Same error regardless of if I'm using the included example or installing it into an existing project.

```
2015-05-15 17:23:03.765 AudioExample[7161:1797587] audio playback loading error: The operation couldn’t be completed. (OSStatus error 2003334207.)
```

Also receive warnings for both AudioRecorderManager.m and AudioPlayerManager.m.

```
#AudioRecorderManager.m:
/Users/Chad/Documents/Work/Dev/react-native-audio/AudioRecorderManager.m:43:13: Unused variable 'time'
```

```
#AudioPlayerManager.m:
/Users/Chad/Documents/Work/Dev/react-native-audio/AudioPlayerManager.m:38:13: Unused variable 'time'
/Users/Chad/Documents/Work/Dev/react-native-audio/AudioPlayerManager.m:80:9: Format string is not a string literal (potentially insecure)
```

Thanks in advance for the help.

**Comment by jsierles** [comment]
Thanks for the report. I'll take a look tomorrow at this and push a fix!

**Comment by jsierles** [comment]
I'll fix the warnings, but the example project is working for me on React Native 0.4.4, recording and playing back the recorded audio. Could you send some more details?

**Comment by jsierles** [comment]
Going to close this issue as I assume it's been fixed. Feel free to reopen with more details!
