### ISSUE TITLE
streaming support (AVPlayer vs AVAudioPlayer ?)

### ISSUE THREAD

**Issue by alfonsodev** [jsierles/react-native-audio#61]
I'm not an Objective-c expert but [I read that AVAudioplayer is not capable of streaming audio](http://stackoverflow.com/questions/13131177/streaming-mp3-audio-with-avplayer)  
Would it be hard to switch to AVPlayer and implement streaming audio capabilities ?

**Comment by jsierles** [comment]
I'm not sure about this, but I'm not actively using this right now and don't need this functionality. Perhaps submit a PR?

Also I believe this component should work with streaming audio: https://github.com/brentvatne/react-native-video

**Comment by jsierles** [comment]
Closing this issue for now. Feel free to continue discussion here or in a PR!
