### ISSUE TITLE
How to delete a file and set up quality and format?

### ISSUE THREAD

**Issue by stoneWeb** [jsierles/react-native-audio#62]
How to delete a file and set up quality and format?

**Comment by alfonsodev** [comment]
For file deletion check the module [react-native-fs](https://github.com/johanneslumpe/react-native-fs#file-deletion)  
For quality and format you have the function `AudioRecorder.prepareRecordingAtPath`
That accept the following arguments:
`path` string
`sampleRate` float default 44100.0
`channels` number, default 2
`quality`, string, possible values "Low", "Medium", "High"
`encoding`, string,  possible values "lpcm", "ima4","aac","MAC3","MAC6","ulaw"
"alaw", ".mp1", ".mp2", ".mp3", "alac"

**Comment by stoneWeb** [comment]
I see,  I saw Audio.ios.js file. Thanks
