### ISSUE TITLE
Can't record .mp3?

### ISSUE THREAD

**Issue by peng051410** [jsierles/react-native-audio#63]
This is my code：
`var audioPath = AudioUtils.DocumentDirectoryPath + '/test.mp3';`
        `console.log(audioPath);`
        `var options = {`
            `AudioEncoding: '.mp3'`
        `};`
`AudioRecorder.prepareRecordingAtPath(audioPath, options);`

but in xcode in found fllow error:

error: The operation couldn’t be completed. (OSStatus error 1718449215.)

what can i do?

**Comment by hartmamt** [comment]
The Problem is kAudioFormatMPEGLayer3 which is not supported by AVAudioRecorder.  We need to remove that option because it is only supported for playback, not recording.

**Comment by hartmamt** [comment]
http://stackoverflow.com/questions/4259078/osstatus-error-1718449215

**Comment by peng051410** [comment]
@hartmamt you mean i can't use this to record mp3?

**Comment by hartmamt** [comment]
Yes that's my understanding.  MP3 isn't supported as a recording format.
