### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by luqin** [jsierles/react-native-audio#64]

**Comment by jsierles** [comment]
Happy to accept PRs for this. I have no need for it as present, but it shouldn't be much work to implement. @hartmamt, did you end up needed Android in the end?

Closing this in favor of a PR, but feel free to keep discussion going here.

**Comment by hartmamt** [comment]
I did, but I am using cordova-media-plugin for it due to time constraints and lack of native Android development knowledge.
