### ISSUE TITLE
any hints about android?

### ISSUE THREAD

**Issue by arisAlexis** [jsierles/react-native-audio#67]
couldn't find anything on google. how can I make this work with Android?

**Comment by yanghuxiao** [comment]
not support for android.

**Comment by jsierles** [comment]
Android is not supported, but if you need it, a PR is welcome to implement it!

**Comment by cpsiaki** [comment]
Any chance of android capabilities getting developed? (what's a PR?) (lol)

**Comment by jsierles** [comment]
https://help.github.com/articles/using-pull-requests/
