### ISSUE TITLE
What is the correct path

### ISSUE THREAD

**Issue by mouneyrac** [jsierles/react-native-audio#70]
Hi,
I am a bit lost. If I put my sound file in /Users/jerome/my_react_native_project_root_folder/src/sounds/sound.m4a 
how should I play it?

I tried many different combination (and file extension caf, wav, m4a) with AudioUtils.DocumentDirectoryPath and AudioUtils.MainBundlePath. Somehow I always ends up with the sound not been played and the log: 

audio playback loading error: The operation couldn’t be completed. (OSStatus error 2003334207.)

I checked the error log in the issues but I could not find an example on how to play a sound that you put in your project (Note that the recorder works perfectly and I can play the file send by the recorder as the recorder give you the full path, I just would like to use this react-native-audio to also play file that I would share in iOS and Android, so for avoiding duplicate they should be in the react native project folders).

cheers,
jerome

**Comment by mouneyrac** [comment]
After tryinh to use react-native-fs I found out you could not open the mainbundle folder. So I went to look in the react-native-sound and found this issue where people explain that you can not put your file in your react native "js" folder (https://github.com/zmxv/react-native-sound/issues/14). So I am guessing we can't either with react-native-audio (especially seen you can't even access the folder from react-native-fr). Closing this issue, I hope it will save some time to others. So basically the solution is to put your file with xcode and in the appropriate android folder (I didn't do it yet). 

Cheers,
Jerome

**Comment by juanpasolano** [comment]
Hi @mouneyrac do you what is the correct folder/steps for android? Thanks
