### ISSUE TITLE
AudioRecorder.onProgress not working when device is locked

### ISSUE THREAD

**Issue by nclaveeoh** [jsierles/react-native-audio#78]
I am trying to check the progress of an audio recording while the app is locked. It works fine in the simulator but not on my test device (5s). I have these lines of code that works as expected when app is running or in background on the device:

`
AudioRecorder.onProgress = (data) => {
            console.log("Tracking audio recording...");
            doStuff();
};
`

I notice that the console stops logging once the device is locked. It will start again if I press the home button. Is this behavior expected or some setting that I have enabled on my device.

Thanks,
Nick

**Comment by nclaveeoh** [comment]
The reason this is happening is the use of CADisplayLink vs NSTimer for the progress timer, see this [SO post](http://stackoverflow.com/questions/32500692/cadislaylink-does-not-trigger-if-device-is-locked). Not sure if this is a bug or "feature". I'm fairly new to the world of iOS development so I'm not sure of ramifications that this change would make. If cool I'd be willing to make the change and submit a pull request.

**Comment by jsierles** [comment]
I'm not sure either, but see no problem in changing this if it works. Please do submit a PR!

**Comment by tolik85** [comment]
Any news on it? I'm still experiencing the issue when the device is locked (doesn't happen when the app simply goes to background).
