### ISSUE TITLE
iOS stops playing audio after stop recording

### ISSUE THREAD

**Issue by benlinton** [jsierles/react-native-audio#85]
When I stop a recording on my iPad Air device, I get the error below:

`ERROR:    [0x16e247000] AVAudioSession.mm:692: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.`

And after that all audio played is silent.  

When I'm in the iOS simulator I have no problems, recordings stop as expected and everything seems to work perfectly.  

I'm playing sound effects within an React Native iOS WebView (using Howler.js v2.0.0) immediately before and after recording, so maybe that's part of the problem?

**Comment by jsierles** [comment]
I'll take a look at this today.

**Comment by benlinton** [comment]
Thanks.  Let me know if you have any questions or need more info.

**Comment by benlinton** [comment]
I did some more testing.  Here's what I found so far:

- I added delays to ensure `Howler.js` and `AudioRecorder` audio were never overlapping.  The error above still gets thrown. 
- Removing `Howler.js` entirely resolves the error.  But I need Howler.js to remain in this project so I'll have to figure something else out.
-  Commenting out `[_recordSession setActive:NO error:nil];` foudn in `AudioRecorderManager.m` resolves the error as well, but there must be a better way than to never sleep the `_recordSession` `AVAudioSession`.

**Comment by benlinton** [comment]
Edited ^

**Comment by benlinton** [comment]
Could part of the problem be that the `AudioRecorderManager.m` doesn't set a `sessionCategory` when it creates an `_audioPlayer` so the session defaults to `AVAudioSessionCategorySoloAmbient`?

```
      _audioPlayer = [[AVAudioPlayer alloc]
        initWithContentsOfURL:_audioRecorder.url
        error:&error];
```

**Comment by jsierles** [comment]
I looked at this a bit, but I'm not really sure what's causing it. I'm not using this plugin now and don't have a lot of time to work on it. I'd like to focus on releasing android support, then come back around to this issue. Let me know meanwhile if you find a solution!

**Comment by benlinton** [comment]
It's gross but adding a delay in between stopping and deactivating the session fixes the problem.

**Original code, not working:**
```
RCT_EXPORT_METHOD(stopRecording)
{
  [_audioRecorder stop];
  [_recordSession setActive:NO error:nil];
  _prevProgressUpdateTime = nil;
}
```

**Delayed working code:**
```
RCT_EXPORT_METHOD(stopRecording)
{
    [_audioRecorder stop];
    _prevProgressUpdateTime = nil;
    [self performSelector:@selector(stopSession) withObject:nil afterDelay:1000];
}

-(void)stopSession
{
  [_recordSession setActive:NO error:nil];
}
```

It seems that `stop` happens async and deactivating the audio session before it's finished can become a race condition issue.  

I tried to deactivate the audio session after the `audioRecorderDidFinishRecording` event so we don't have to use a gross delay.  But recorder `stop` seems to still still be doing it's thing after the `audioRecorderDidFinishRecording` event is triggered.  Possibly encoding the audio?  Who knows.

**Comment by benlinton** [comment]
^ Edited on github.

**Comment by jsierles** [comment]
Is this still happening?

**Comment by johnbryant** [comment]
I have the same problem too. After I stop the record, I can not play all the media file (video and audio)

**Comment by jsierles** [comment]
@benlinton if you're still seeing this, can you submit a PR with this change? Ideally the delay could be configurable.

**Comment by benlinton** [comment]
I imagine so, but I haven't been working with this library for the last few months so I can't say for sure.

**Comment by VansonLeung** [comment]
Just encountered this problem when developing a chat app

**Comment by HermitCarb** [comment]
I have the same problem too. I read library react-native-audio and [react-native-sound](https://github.com/zmxv/react-native-sound) native code. I find this:

- When react-native-audio stop recording, it set `AVAudioSession` to be inactive in file `AudioRecorderManager.m`
```
RCT_EXPORT_METHOD(stopRecording)
{
  [_audioRecorder stop];
  [_recordSession setActive:NO error:nil];
  _prevProgressUpdateTime = nil;
}
```
- Then use [react-native-sound](https://github.com/zmxv/react-native-sound) to play audio file. It sames like the `AVAudioSession` isn't set to be active. 

So, After added this code in my javascript file. It worked :

```
if (Platform.OS == 'ios') {  SoundPlayer.enableInSilenceMode(true);}    // <---- this line
this.soundPlayer = new Sound(filename, SoundPlayer.DOCUMENT, (error) => {
  ...
}
```

I think it's good manners that setting AVAudioSession to be active before creating a new instance of Sound and setting to be inactive after creating fail, playing fail and playing success. 

Hope to be helpful.

**Comment by johnbryant** [comment]
@HermitCarb it worked for me, thank u~

**Comment by jsierles** [comment]
Looks like this is solved, so closing.
