### ISSUE TITLE
AudioRecorder expose requestRecordPermission

### ISSUE THREAD

**Issue by benlinton** [jsierles/react-native-audio#87]
It would be nice if the `AudioRecorder` object found in `Audio.ios.js` would expose the native `requestRecordPermission` method so we can easily request microphone access on application load.

See this for more info on the native `requestRecordPermission` method:
https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/#//apple_ref/doc/uid/TP40008240-CH1-SW45

Thanks!

**Comment by benlinton** [comment]
And possibly expose the `recordPermission` status method as well.

**Comment by benlinton** [comment]
And possibly expose the `recordPermission` status method as well.

**Comment by jsierles** [comment]
This sounds reasonable - could you work on a pull request for it?

**Comment by jsierles** [comment]
Closing per email discussion about submitting a pull request.
