### ISSUE TITLE
Not playing multiple sounds

### ISSUE THREAD

**Issue by vaibhawc** [jsierles/react-native-audio#90]
Since I am new to iOS AVAudioSession, do you think it is possible to play multiple sounds through this library? I tried but failed, is it like AVAudioSession doesn't allow it, or is it the way it has been implemented?

**Comment by jsierles** [comment]
This is likely due to only having access to a single instance of the session via the React Native bridge. I'd recommend using [react-native-sound](https://github.com/zmxv/react-native-sound) for playback. Eventually we want to integrate with this library.
