### ISSUE TITLE
getDurationFromPath not exist in native method(ios)

### ISSUE THREAD

**Issue by zzycami** [jsierles/react-native-audio#94]
When I call getDurationFromPath in Audio.ios.js at AudioPlayer, The error tell me ''AudioPlayerManager.getDurationFromPath" is not a function. Then I check the native in ios, method getDurationFromPath actually not exist. chould you add this method or delete this method from  Audio.ios.js

**Comment by zzycami** [comment]
"react": "15.3.1",
    "react-dom": "15.3.1",
    "react-native": "0.32.0",
    "react-native-audio": "^2.0.0",

**Comment by jsierles** [comment]
This is an Android-only method at the moment, so I don't to remove it. Would you be interested in implementing on iOS?

**Comment by zzycami** [comment]
Fine, I add this method recently.
