### ISSUE TITLE
Question: saving audio files

### ISSUE THREAD

**Issue by Slooowpoke** [jsierles/react-native-audio#97]
Less of an issue, more of a question.

The plugin works great. However I am struggling to find where the audio files save to, is it a temporary location for playback? Or do these files get put somewhere special? Playback is working fine but I'm wondering where it is playing from.

Should I be using something like react-native-fs for saving the file?

**Comment by RakanNimer** [comment]
Hey !

This plugin offers an AudioUtils object that exposes directories in which you can save. 

### Android
```
MainBundlePath
CachesDirectoryPath
DocumentDirectoryPath
LibraryDirectoryPath
PicturesDirectoryPath
MusicDirectoryPath
DownloadsDirectoryPath
```

### iOS
```
MainBundlePath
CachesDirectoryPath
DocumentDirectoryPath
LibraryDirectoryPath
```

This component should be enough if you just want to save the file locally :

```js
import { AudioUtils, AudioRecorder, AudioPlayer } from 'react-native-audio';
const myAudioRecorder = {
  record(audioFileName){
    const audioPath = AudioUtils.DocumentDirectoryPath+audioFileName;
    AudioRecorder.prepareRecordingAtPath(audioPath, {
      SampleRate: 22050,
      Channels: 1,
      AudioQuality: "Low",
      AudioEncoding: "aac"
    });
  }
  play(audioFileName){
    const audioPath = AudioUtils.DocumentDirectoryPath+audioFileName;
    // Promise only in android for now.
    AudioPlayer.play(audioPath).then(play => {
        }).catch((err)=>{
          console.warn(err);});
        })
  }
};
```

If you want to upload and download voice files then using react-native-fs would be a great idea.

Cheers !

**Comment by Slooowpoke** [comment]
Will this show up when browsing the file system? The files are perfect for playback but I can't seem to find them anywhere?

Thank you.

**Comment by RakanNimer** [comment]
Fixed the example I forgot to add startRecording. 
After recording it creates the file at ```AudioUtils.DocumentDirectoryPath+audioFileName```
Log the variable to check where the file is stored.

**Comment by Slooowpoke** [comment]
Thank you sooooo much! I found them with ease. I struggled with finding the files when browsing using the computer's file browser but when I checked on the phone with a file explorer there it was sitting there. Thanks a ton.

**Comment by RakanNimer** [comment]
You're welcome :) 
Cheers !

**Comment by franzejr** [comment]
@RakanNimer, are you sure MainBundlePath is working for Android? https://github.com/jsierles/react-native-audio/blob/9d5e36e31831a2ef1ae7272d4c3141c945dfd89b/android/src/main/java/com/rnim/rn/audio/AudioRecorderManager.java#L63
