### ISSUE TITLE
Add iOS 10 instruction in README to add NSMicrophoneUsageDescription to plist

### ISSUE THREAD

**Issue by neilsarkar** [jsierles/react-native-audio#98]
Full error message:

This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by RakanNimer** [comment]
You should add this : 
```
<key>NSMicrophoneUsageDescription</key>
<string>This sample uses the microphone to record your speech and convert it to text.</string>
```
to your info.plist file. At the top level dict ( Xcode edit source of info.plist )
We should probably add this to the README.

**Comment by neilsarkar** [comment]
Yep was about to add that that's what I did :) thanks!

**Comment by RakanNimer** [comment]
Thanks for reporting this !

**Comment by neilsarkar** [comment]
no problem, thanks for providing the components!
